# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qccvhcJgUP6NNcL6Gl5SkXeRzzAXB4Bp
"""

pip install git+https://git@github.com/ping/instagram_private_api.git@1.6.0

import ast
from instagram_private_api import Client, ClientCompatPatch
import json

user_name = input('username ')
password = input('password ')
api = Client(user_name, password,auto_patch=True)
print("connexion succes")

results ='['

y=True
print('entrez le username des comptes instagram que vous voulez afficher leurs infos \net finissez par entrer "0"\n')

while(y==True):
    x = input()
    if x!='0':
        results = results + str(api.username_info(x)) +','
    else:
        results=results[:-1]+']'
        y=False


results = ast.literal_eval(results)
print(results)

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/My Drive/insta', 'w') as jsonFile:
    json.dump(results, jsonFile)

with open('/content/drive/My Drive/insta', 'r') as jsonFile:
    k = json.load(jsonFile)
    print(k)
print (type(k))
for y in k :
  print(y['user'])
  print(type(y))
  print(y['user']['pk'])

import sqlite3
BDD = sqlite3.connect('intagram.db')
curseur = BDD.cursor()
req_create = "CREATE TABLE User(id BIGINT INT8	 PRIMARY KEY,username TEXT,fullname TEXT, privacy BOOLEAN, follower INTEGER, following INTEGER, profile_picture TEXT, bio TEXT,media INTEGER)"
curseur.execute(req_create)
BDD.commit()
y=k[0]
print(type(y))
x=y['user']
print(type(x))
for y in k :
   print(y)
   x=y['user']
   curseur.execute("INSERT INTO Users (id,username,fullname,privacy,follower,following,profile_picture,bio,media) VALUES (:pk,:username,:full_name,:is_private,:follower_count,:following_count,:profile_pic_url,:biography,:media_count)",x)
BDD.commit()
print("successfully collected data from Instagram")